# Generated by Django 3.2.7 on 2021-10-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
