# Generated by Django 3.2.7 on 2021-10-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_entry_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.CharField(choices=[('AR', 'LeetCode'), ('HM', 'HackerRank'), ('ST', 'Codewars'), ('LL', 'Codeforces'), ('SQ', 'CodeChef'), ('TR', 'CodeChef'), ('GR', 'CodeChef'), ('SO', 'CodeChef'), ('SE', 'CodeChef'), ('GY', 'CodeChef'), ('RB', 'CodeChef'), ('DP', 'CodeChef'), ('BM', 'CodeChef'), ('O', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.CharField(choices=[('LC', 'LeetCode'), ('HR', 'HackerRank'), ('CW', 'Codewars'), ('O', 'Other')], max_length=200, null=True),
        ),
    ]
