# Generated by Django 3.2.7 on 2021-12-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211015_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.CharField(choices=[('LeetCode', 'LeetCode'), ('HackerRank', 'HackerRank'), ('Codewars', 'Codewars'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.CharField(choices=[('Arrays', 'Arrays'), ('Hashmaps', 'Hashmaps'), ('Strings', 'Strings'), ('Linked Lists', 'Linked Lists'), ('Stacks/Queues', 'Stacks/Queues'), ('Trees', 'Trees'), ('Graphs', 'Graphs'), ('Sorting', 'Sorting'), ('Searching', 'Searching'), ('Greedy', 'Greedy'), ('Recursion/Backtracking', 'Recursion/Backtracking'), ('Dynamic Programming', 'Dynamic Programming'), ('Bit Manipulation', 'Bit Manipulation'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
